### PR TITLE
updates devDependencies to eliminate moderate / critical security issues

### LINKED ISSUE #7: [Bug] Moderate and critical vulnerabilities in dependent packages
**Describe the bug**

There a moderate and high security vulnerabilities in the dependency packages.
```
found 147 vulnerabilities (65 low, 70 moderate, 12 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**To Reproduce**
1. Go to terminal
2. run `npm install`
3. See error

**Expected behavior**

There should not be any moderate or high vulnerabilities if it can be avoided.

**Server (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Additional context**

### PR DESCRIPTION
**Pull request by dmvt**
## Proposed changes

The `npm-check-updates` package is currently out of date and contains many vulnerabilities.

Before this PR:
```
found 147 vulnerabilities (65 low, 70 moderate, 12 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

After this PR:
```
found 63 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [X] I have read the [CONTRIBUTING](https://docs.ark.io/developers/guidelines/contributing.html) documentation
- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

Testing is (obviously) not required for this update.
Resolves https://github.com/ArkEcosystem/core-plugin-skeleton/issues/7

### CODE REVIEW

**Comment by ghost** [comment]
**Thanks for submitting this pull request!** A maintainer will review this in the next few days and explicitly select labels so you know what's going on.

_If no reviewer appears after a week, a reminder will be sent out._

**Comment by ghost** [comment]
Your pull request doesn't follow our [contribution guidelines](https://docs.ark.io/guidebook/contribution-guidelines/). Please review and correct it.

**Review by faustbrian — APPROVED** [review]

**Comment by ghost** [comment]
A contributor has approved this PR. A maintainer will merge this PR shortly. If it shouldn't be merged yet, please leave a comment saying so and we'll wait.

_Thank you for your contribution!_

**Comment by ghost** [comment]
Your pull request has been merged and marked as tier 5. _It will earn you $5 USD._

**Comment by boldninja** [comment]
@dmvt Can you provide me with your ARK address for GitHub bounty? You can also contact me on ARK's Slack - https://ark.io/slack (username : boldninja) and direct message me your address there.

**Pull request merged**
